import { Inter,Fira_Code,Poppins } from "next/font/google";
import "./globals.css";
// import { Provider } from "./utils/Provider";
import Navbar from "../components/Navbar";
import { Provider } from "../utils/Provider";

const inter = Inter({ subsets: ["latin"] });
// adding fircode
const FiraCode = Fira_Code({ subsets: ["latin"] });
// const Poppin = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${FiraCode.className} h-full  bg-amber-50  text-indigo-950  dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-pink-500 `}>
        <Provider>
          <Navbar />
          <main className=" mx-auto  max-w-5xl px-24">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
